# Pandas Revision

Syntax on `placement.csv`, practice on `food_orders.csv`.

In [30]:
import pandas as pd

df = pd.read_csv('placement.csv')      # syntax examples
food = pd.read_csv('food_orders.csv')  # practice

---
## 1. First look

In [31]:
# size: (rows, columns)
df.shape

(550, 12)

In [32]:
# numeric summary: count, mean, min, max
df.describe().round(2)

,cgpa,twelfth_percent,internships,projects,backlogs,prep_hours,communication_score,package_lpa
count,550.00,550.00,519.00,550.00,550.00,454.00,538.00,517.00
mean,7.36,77.60,1.30,2.56,0.68,153.15,6.27,4.71
std,0.98,10.12,1.18,1.49,1.10,86.06,1.69,3.48
min,5.00,55.00,0.00,0.00,0.00,16.00,1.10,0.00
25%,6.69,70.90,0.00,1.00,0.00,90.00,5.20,0.00
50%,7.40,77.90,1.00,2.00,0.00,134.00,6.30,6.01
75%,7.98,84.50,2.00,4.00,1.00,192.75,7.40,7.28
max,10.00,98.00,4.00,6.00,4.00,500.00,10.00,12.56

In [33]:
# column types and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   student_id           550 non-null    object
 1   cgpa                 550 non-null    float64
 2   twelfth_percent      550 non-null    float64
 3   branch               550 non-null    object
 4   internships          519 non-null    float64
 5   projects             550 non-null    int64
 6   backlogs             550 non-null    int64
 7   prep_hours           454 non-null    float64
 8   communication_score  538 non-null    float64
 9   hostel               550 non-null    object
 10  placed               550 non-null    object
 11  package_lpa          517 non-null    float64
dtypes: float64(6), int64(2), object(4)
memory usage: 51.7+ KB

### Practice

**Q1.** How many orders are in the file, and how many details are stored for each order?

In [34]:
df.shape #shape is done to get the no. of rows and cols so for how many orders its row and for there details its column

(550, 12)

**Q2.** Someone ordered food worth a small EMI. Find the biggest order value and the longest delivery time using one command.

In [ ]:
#food.info()
print(food[['order_value', 'delivery_time_min']].max()) 
#double square bracket is used for col selection bcz max mai sirf 1 he cheez ja skti h so by using double sq brak we use it

order_value          2354
delivery_time_min      63
dtype: int64

**Q3.** Which columns hold numbers and which hold text?

---
## 2. Selecting

In [ ]:
# one column
df['cgpa']

0      7.41
1      7.52
2      7.35
3      7.86
4      5.63
       ...
545    8.40
546    7.60
547    6.33
548    8.86
549    8.45
Name: cgpa, Length: 550, dtype: float64

In [ ]:
# many columns: a list inside [ ]
df[['branch', 'cgpa', 'placed']].head()

  branch  cgpa placed
0     IT  7.41     No
1    CSE  7.52    Yes
2    CSE  7.35    Yes
3    CSE  7.86    Yes
4    CSE  5.63    Yes

In [ ]:
# iloc: by position -> rows, columns
df.iloc[0:5, 0:3]

  student_id  cgpa  twelfth_percent
0     VS2821  7.41             78.5
1     VS3068  7.52             70.0
2     VS2940  7.35             78.3
3     VS3138  7.86             60.2
4     VS2670  5.63             88.3

In [ ]:
# loc: by label -> rows, column names (both ends included)
df.loc[0:4, 'cgpa':'internships']

   cgpa  twelfth_percent branch  internships
0  7.41             78.5     IT          0.0
1  7.52             70.0    CSE          2.0
2  7.35             78.3    CSE          2.0
3  7.86             60.2    CSE          1.0
4  5.63             88.3    CSE          2.0

### Practice

**Q4.** The manager's eyes hurt after 13 columns. Show only `city`, `cuisine` and `order_value` for the first 10 orders.

**Q5.** The printer jammed and printed only rows 50 to 54, first 5 columns. Recreate that page using positions.

**Q6.** Using labels, show rows 100 to 105 and every column from `city` to `order_hour`.

---
## 3. Filtering and sorting

In [ ]:
# one condition
df[df['cgpa'] > 8]

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
14,VS2701,9.01,64.8,ECE,1.0,0,1,NaN,4.8,Yes,Yes,6.70
16,VS3012,8.29,77.8,CSE,0.0,2,0,81.0,7.9,Yes,Yes,8.06
17,VS2892,8.84,86.3,Civil,1.0,2,0,132.0,3.4,No,Yes,5.77
18,VS2936,8.23,69.5,CSE,3.0,3,1,119.0,6.9,Yes,Yes,8.54
21,VS2930,8.07,83.1,Mech,1.0,2,0,120.0,9.5,Yes,Yes,5.38
...,...,...,...,...,...,...,...,...,...,...,...,...
537,VS2668,8.21,74.2,CSE,0.0,4,0,157.0,5.5,Yes,Yes,7.66
539,VS2966,8.45,80.9,Mech,2.0,2,1,90.0,7.6,No,Yes,7.31
545,VS2811,8.40,79.7,ECE,1.0,4,0,173.0,5.0,Yes,Yes,6.22
548,VS2796,8.86,78.2,ECE,3.0,1,0,259.0,6.4,Yes,Yes,7.51
549,VS2775,8.45,70.7,CSE,0.0,3,0,NaN,5.1,Yes,Yes,8.45

In [ ]:
# two conditions: & is and, | is or, each in its own ( )
df[(df['cgpa'] > 8) & (df['backlogs'] == 0)]

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
16,VS3012,8.29,77.8,CSE,0.0,2,0,81.0,7.9,Yes,Yes,8.06
17,VS2892,8.84,86.3,Civil,1.0,2,0,132.0,3.4,No,Yes,5.77
21,VS2930,8.07,83.1,Mech,1.0,2,0,120.0,9.5,Yes,Yes,5.38
44,VS3139,8.85,81.2,Mech,0.0,3,0,194.0,7.4,No,Yes,6.89
47,VS2788,8.09,84.6,Mech,0.0,2,0,220.0,6.0,Yes,No,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
534,VS3112,8.37,63.9,CSE,4.0,2,0,103.0,5.9,Yes,Yes,7.52
537,VS2668,8.21,74.2,CSE,0.0,4,0,157.0,5.5,Yes,Yes,7.66
545,VS2811,8.40,79.7,ECE,1.0,4,0,173.0,5.0,Yes,Yes,6.22
548,VS2796,8.86,78.2,ECE,3.0,1,0,259.0,6.4,Yes,Yes,7.51
549,VS2775,8.45,70.7,CSE,0.0,3,0,NaN,5.1,Yes,Yes,8.45

In [ ]:
# value is one of many
df[df['branch'].isin(['CSE', 'IT'])]

# value inside a range (both ends included)
df[df['cgpa'].between(7, 8)]

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
0,VS2821,7.41,78.5,IT,0.0,6,1,188.0,4.3,No,No,0.00
1,VS3068,7.52,70.0,CSE,2.0,3,0,167.0,9.8,Yes,Yes,10.06
2,VS2940,7.35,78.3,CSE,2.0,0,3,199.0,4.8,Yes,Yes,NaN
3,VS3138,7.86,60.2,CSE,1.0,3,0,135.0,8.0,No,Yes,8.63
6,VS2971,7.79,74.7,CSE,0.0,4,0,NaN,7.3,Yes,No,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
536,VS3032,7.53,83.5,ECE,0.0,2,3,20.0,6.7,No,No,0.00
542,VS2998,7.81,63.4,IT,4.0,4,0,89.0,5.1,Yes,Yes,8.52
543,VS2785,7.19,77.5,ECE,3.0,4,0,84.0,6.5,No,Yes,6.68
544,VS2948,7.18,87.2,ECE,NaN,1,1,296.0,4.2,Yes,No,0.00
546,VS3102,7.60,76.5,Civil,0.0,4,0,NaN,6.7,Yes,Yes,5.68

In [ ]:
# count of each category
df['branch'].value_counts()

branch
CSE      167
IT       118
ECE      112
Mech     103
Civil     50
Name: count, dtype: int64

In [ ]:
# sort, biggest first
df.sort_values('cgpa', ascending=False).head()

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
113,VS3148,10.00,93.9,Mech,3.0,3,0,190.0,6.8,Yes,Yes,9.17
500,VS2917,10.00,84.0,ECE,0.0,4,0,58.0,6.3,No,Yes,8.54
265,VS2702,9.95,86.5,CSE,2.0,0,0,248.0,7.0,No,Yes,10.03
185,VS3124,9.85,63.8,CSE,0.0,4,0,87.0,7.5,Yes,Yes,8.77
157,VS2747,9.78,85.3,ECE,2.0,2,0,NaN,5.3,Yes,Yes,NaN

### Practice

**Q7.** Biryani at 2 AM is not hunger, it is a lifestyle. Count the Biryani orders placed between midnight and 3 AM (hours 0 to 3).

**Q8.** Someone in Pune is clearly throwing a party. Show Pune orders worth more than 1000 rupees. How many?

**Q9.** A food blogger survives only on Pizza and Burger. How many such orders are there?

**Q10.** How many deliveries fell in the *"bhaiya, kahan ho?"* zone of 30 to 45 minutes?

**Q11.** Does anyone still pay in cash? Count the orders by payment method.

**Q12.** Someone definitely ordered for the whole hostel. Show the 5 biggest orders with `city`, `cuisine`, `quantity` and `order_value`.

**Q13.** Which delivery partners were basically The Flash? Show the 5 fastest deliveries with `city`, `distance_km` and `delivery_time_min`.

---
## 4. Cleaning

In [ ]:
# blanks per column
df.isnull().sum()

student_id              0
cgpa                    0
twelfth_percent         0
branch                  0
internships            31
projects                0
backlogs                0
prep_hours             96
communication_score    12
hostel                  0
placed                  0
package_lpa            33
dtype: int64

In [ ]:
# repeated rows
print(df.duplicated().sum())

# remove repeated rows
df_clean = df.drop_duplicates()

0

In [ ]:
# remove rows where one column is blank
df_clean = df_clean.dropna(subset=['internships'])

# fill blanks with a value
df_clean['prep_hours'] = df_clean['prep_hours'].fillna(0)

# change the type
df_clean['internships'] = df_clean['internships'].astype(int)

In [ ]:
# new column from existing columns
df_clean['cgpa_percent'] = (df_clean['cgpa'] * 9.5).round(1)
df_clean[['cgpa', 'cgpa_percent']].head()

   cgpa  cgpa_percent
0  7.41          70.4
1  7.52          71.4
2  7.35          69.8
3  7.86          74.7
4  5.63          53.5

### Practice

**Q14.** Count the blanks in every column.

**Q15.** The app got confused and saved some orders twice. How many repeated rows are there?

**Q16.** Remove the repeated orders before customers get charged twice. Print the shape.

**Q17.** GPS failed for some orders, so the delivery partner took the scenic route. Remove the rows with a blank `distance_km` and print the shape.

**Q18.** A blank tip means no tip, and one sad delivery partner. Fill the blanks in `tip` with 0 and make it a whole number.

**Q19.** Add a column `value_per_item`: order value divided by quantity, rounded.

---
## 5. Grouping and saving

In [ ]:
# average per group
df.groupby('branch')['cgpa'].mean()

branch
CSE      7.484431
Civil    7.341200
ECE      7.377054
IT       7.183051
Mech     7.342233
Name: cgpa, dtype: float64

In [ ]:
# sorted, highest first
df.groupby('branch')['cgpa'].mean().sort_values(ascending=False)

branch
CSE      7.484431
ECE      7.377054
Mech     7.342233
Civil    7.341200
IT       7.183051
Name: cgpa, dtype: float64

In [ ]:
# other numbers per group
df.groupby('branch')['cgpa'].max()
df.groupby('branch')['internships'].sum()
df.groupby('branch')['student_id'].count()

branch
CSE      167
Civil     50
ECE      112
IT       118
Mech     103
Name: student_id, dtype: int64

In [ ]:
# save to a file, without the index column
df_clean.to_csv('placement_clean.csv', index=False)

### Practice

**Q20.** Which city is the stingiest tipper? Find the average tip per city, lowest first.

**Q21.** Is the weekend really a party? Find the average order value for each day, highest first.

**Q22.** Does a late delivery earn an angry rating? Compare the average rating of late and on-time orders.

**Q23.** Which city holds the record for the single biggest order after cleaning? Find the highest order value in each city.

**Q24.** Which payment method brings in the most money? Find the total order value for each payment method.

**Q25.** Which cuisine is the nation's favourite? Count the orders for each cuisine.

**Q26.** Save the cleaned data as `food_orders_clean.csv` without the index column.

---
*Q16 to Q19 change `food`. Run them only once, in order.*